# Generated by Django 5.1.4 on 2024-12-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='image/', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'баннер',
                'verbose_name_plural': 'баннера',
            },
        ),
        migrations.DeleteModel(
            name='Main',
        ),
    ]
